namespace sprites.tinyTown {
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_36 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_48 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_57 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_58 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_59 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_60 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_61 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_62 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_63 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_64 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_65 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_66 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_67 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_68 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_69 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_70 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_71 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_72 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_73 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_74 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_75 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_76 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_77 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_78 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_79 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_80 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_81 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_82 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_83 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_84 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_85 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_86 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_87 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_88 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_89 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_90 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_91 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_92 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_93 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_94 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_95 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_96 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_97 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_98 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_99 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_100 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_101 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_102 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_103 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_104 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_105 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_106 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_107 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_108 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_109 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_110 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_111 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_112 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_113 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_114 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_115 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_116 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_117 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_118 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_119 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_120 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_121 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_122 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_123 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_124 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_125 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_126 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_127 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_128 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_129 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_130 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyTown"
    export const tinyTown_tinyTown_131 = image.ofBuffer(hex``);
}
