namespace sprites.tinyDungeon {
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_36 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_37 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_38 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_39 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_40 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_41 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_42 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_43 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_44 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_45 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_46 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_47 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_48 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_49 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_50 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_51 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_52 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_54 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_55 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_56 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_57 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_58 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_59 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_60 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_61 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_62 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_63 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_64 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_65 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_66 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_67 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_68 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_69 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_70 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_71 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_72 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_73 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_74 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_75 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_76 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_77 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_78 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_79 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_80 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_81 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_82 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_83 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_84 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_85 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_86 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_87 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_88 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_89 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_90 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_91 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_92 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_93 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_94 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_95 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_96 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_97 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_98 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_99 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_100 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_101 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_102 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_103 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_104 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_105 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_106 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_107 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_108 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_109 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_110 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_111 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_112 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_113 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_114 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_115 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_116 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_117 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_118 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_119 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_120 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_121 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_122 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_123 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_124 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_125 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_126 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_127 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_128 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_129 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_130 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-TinyDungeon"
    export const tinyDungeon_tinyDungeon_131 = image.ofBuffer(hex``);
}
